// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyncChain.API.Data;

#nullable disable

namespace SyncChain.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("AddProductPricingAndImageFields")]
    partial class AddProductPricingAndImageFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaDonHang");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("SyncChain.API.Models.GiaoDichKho", b =>
                {
                    b.Property<int>("MaGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("TEXT");

                    b.HasKey("MaGiaoDich");

                    b.HasIndex("MaSanPham");

                    b.ToTable("GiaoDichKho");
                });

            modelBuilder.Entity("SyncChain.API.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("SyncChain.API.Models.PhanQuyen", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaVaiTro");

                    b.ToTable("PhanQuyen");
                });

            modelBuilder.Entity("SyncChain.API.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinhAnhUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MucTonThap")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaSanPham");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("ChiTietDonHang", b =>
                {
                    b.HasOne("DonHang", "DonHang")
                        .WithMany("ChiTietDonHang")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SyncChain.API.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DonHang", b =>
                {
                    b.Navigation("ChiTietDonHang");
                });

            modelBuilder.Entity("SyncChain.API.Models.GiaoDichKho", b =>
                {
                    b.HasOne("SyncChain.API.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
